### ISSUE TITLE
Add configurations which include all minor releases

### ISSUE THREAD

**Issue by dominykas** [nodejs/ci-config-travis#10]
Some folks would likely want to have a larger test matrix based on their version support needs, at the cost of slower builds / more build minutes.

As suggested in #5, this could be done as a sub-folder inside a strategy folder, or it can be done as a suffix, e.g. `gte-N-minors.yml`.

This could somewhat address the "people should test in N.0.0" case (for packages that declare their `engines` support as `>= N` / `N.x`), to avoid accidentally breaking downstream users by using features available only in the latest releases (points raised in https://github.com/nodejs/ci-config-travis/pull/6#issuecomment-660780430 and the remaining discussion).

**Comment by ljharb** [comment]
I already use this on https://github.com/ljharb/travis-ci/tree/master/node/minors in most of my packages; it seems useful.
