### ISSUE TITLE
Rename primary branch to main

### ISSUE THREAD

**Issue by mhdawson** [nodejs/ci-config-travis#16]
We are going through all of the node.js repositories to rename the primary branch to main. Please see nodejs/node#33864 for more context.

I don't think there should be any issues for the contributors to this repo. I'd like to do the remain this Friday May 22nd unless there are any concerns.

Please let me know in this issue before May 22nd if there are any concerns, otherwise I'll go ahead and do the change.

@dominykas

**Comment by dominykas** [comment]
This would cause trouble for anyone importing @master... I don't think there are any usages of that, but I will verify that.

**Comment by ljharb** [comment]
It shouldn't if we use github's tools; requests for a deleted master branch will transparently redirect to main.

**Comment by dominykas** [comment]
There's nobody I could find with `@master`, so this is good to go regardless of the redirect 👍 

I don't have access to make the change.

**Comment by mhdawson** [comment]
Branch renamed, closing.
